version: "3.9"

services:
  xray:
    build: .
    container_name: xray-wrapper
    restart: always
    env_file: .env
    environment:
      - TZ=Europe/Amsterdam
      - XRAY_PORT=${XRAY_PORT:-443}
      - API_PORT=${API_PORT:-440}
    volumes:
      - ./xray/data:/xray/data
      - ./xray/logs:/xray/logs
    ports:
      - ${XRAY_PORT:-443}:${XRAY_PORT:-443}
      - ${API_PORT:-440}:${API_PORT:-440}
